goog.provide('dcs.prototype_6.status');
dcs.prototype_6.status.ele = (function dcs$prototype_6$status$ele(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,a2,b2,c2){
var num = cljs.core.count(cljs.core.filter.cljs$core$IFn$_invoke$arity$2(cljs.core.nil_QMARK_,new cljs.core.PersistentVector(null, 29, 5, cljs.core.PersistentVector.EMPTY_NODE, [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,a2,b2,c2], null)));
var s__$1 = ((cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2((0),num))?"":new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"span.icon-text","span.icon-text",1208576291),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"span.icon","span.icon",-1181275586),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"i.fas.fa-spinner.fa-pulse","i.fas.fa-spinner.fa-pulse",1605646997)], null)], null),[" please wait - loading/deriving ",cljs.core.str.cljs$core$IFn$_invoke$arity$1(num)," datasets"].join('')], null));
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"p","p",151049309),s__$1], null)], null);
});
dcs.prototype_6.status.root = (function dcs$prototype_6$status$root(){
return new cljs.core.PersistentVector(null, 30, 5, cljs.core.PersistentVector.EMPTY_NODE, [dcs.prototype_6.status.ele,cljs.core.deref(dcs.prototype_6.state.geojson_cursor),cljs.core.deref(dcs.prototype_6.state.meta_derivation_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_generation_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_percent_recycled_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_management_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_composition_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_generation_positions_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_percent_recycled_positions_cursor),cljs.core.deref(dcs.prototype_6.state.household_co2e_derivation_generation_cursor),cljs.core.deref(dcs.prototype_6.state.household_co2e_derivation_generation_positions_cursor),cljs.core.deref(dcs.prototype_6.state.business_waste_by_region_derivation_generation_cursor),cljs.core.deref(dcs.prototype_6.state.business_waste_by_region_derivation_composition_cursor),cljs.core.deref(dcs.prototype_6.state.waste_site_derivation_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_generation_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_composition_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_percent_recycled_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_missed_bins_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_community_food_tonnes_derivation_tonnes_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_community_food_tonnes_derivation_flow_cursor),cljs.core.deref(dcs.prototype_6.state.stirling_community_food_footfall_derivation_cursor),cljs.core.deref(dcs.prototype_6.state.fairshare_material_derivation_cursor),cljs.core.deref(dcs.prototype_6.state.fairshare_co2e_derivation_cursor),cljs.core.deref(dcs.prototype_6.state.ace_furniture_counts_derivation_orig_cursor),cljs.core.deref(dcs.prototype_6.state.ace_furniture_counts_derivation_category_trends_cursor),cljs.core.deref(dcs.prototype_6.state.ace_furniture_counts_derivation_item_trends_cursor),cljs.core.deref(dcs.prototype_6.state.ace_furniture_weights_derivation_orig_cursor),cljs.core.deref(dcs.prototype_6.state.ace_furniture_weights_derivation_flights_per_category_cursor),cljs.core.deref(dcs.prototype_6.state.ace_furniture_weights_derivation_flights_per_item_cursor),cljs.core.deref(dcs.prototype_6.state.household_waste_analysis_derivation_cursor)], null);
});

//# sourceMappingURL=dcs.prototype_6.status.js.map
