goog.provide('dcs.prototype_6.status');
dcs.prototype_6.status.ele = (function dcs$prototype_6$status$ele(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o){
var num = cljs.core.count(cljs.core.filter.cljs$core$IFn$_invoke$arity$2(cljs.core.nil_QMARK_,new cljs.core.PersistentVector(null, 15, 5, cljs.core.PersistentVector.EMPTY_NODE, [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o], null)));
var s = ((cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2((0),num))?"":["Loading/deriving ",cljs.core.str.cljs$core$IFn$_invoke$arity$1(num)," datasets..."].join(''));
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"p","p",151049309),s], null)], null);
});
dcs.prototype_6.status.root = (function dcs$prototype_6$status$root(){
return new cljs.core.PersistentVector(null, 16, 5, cljs.core.PersistentVector.EMPTY_NODE, [dcs.prototype_6.status.ele,cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_generation_holder),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_percent_recycled_holder),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_management_holder),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_composition_holder),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_generation_positions_holder),cljs.core.deref(dcs.prototype_6.state.household_waste_derivation_percent_recycled_positions_holder),cljs.core.deref(dcs.prototype_6.state.household_co2e_derivation_generation_holder),cljs.core.deref(dcs.prototype_6.state.household_co2e_derivation_generation_positions_holder),cljs.core.deref(dcs.prototype_6.state.business_waste_by_region_derivation_generation_holder),cljs.core.deref(dcs.prototype_6.state.business_waste_by_region_derivation_composition_holder),cljs.core.deref(dcs.prototype_6.state.waste_site_derivation_holder),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_generation_holder),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_composition_holder),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_percent_recycled_holder),cljs.core.deref(dcs.prototype_6.state.stirling_bin_collection_derivation_missed_holder)], null);
});

//# sourceMappingURL=dcs.prototype_6.status.js.map
